title: Zilin Jiang
email: libragold@gmail.com
description: "Mathematician with a crush on the web"
baseurl: ""
url: "http://www.zilin.one"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules
  - vendor

paginate: 9
paginate_path: "/blog/page/:num/"

googleAnalyticsId: UA-110604791-1

plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jemoji

excerpt_separator: <!--more-->

future: true

# Serving
detach:  false
port:    4100
host:    0.0.0.0
